apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: deploy-rollupdate
  name: deploy-rollupdatekubtest1
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0%
      maxSurge:  100%
  selector:
    matchLabels:
      app: deploy-rollupdate
  template:
    metadata:
      labels:
        app: deploy-rollupdate
    spec:
      containers:
        - image: 'swr.troila.com/test/test:1.1'
          imagePullPolicy: IfNotPresent
          name: tomcat
      restartPolicy: Always

